# Generated by Django 4.0.4 on 2023-01-07 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('input1', models.CharField(max_length=100)),
                ('input2', models.CharField(max_length=100)),
                ('input3', models.CharField(max_length=100)),
                ('input4', models.CharField(max_length=100)),
                ('input5', models.CharField(max_length=100)),
                ('input6', models.CharField(max_length=100)),
                ('input7', models.CharField(max_length=100)),
            ],
        ),
    ]
