# Generated by Django 4.0.4 on 2023-01-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='input1',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='input2',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='input3',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='input4',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='input5',
            new_name='schcol',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='input6',
            new_name='seds',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='input7',
            new_name='uni',
        ),
    ]
