# Generated by Django 4.0.4 on 2023-01-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_input1_database_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='proof',
            field=models.ImageField(default='image', upload_to='proof_images'),
            preserve_default=False,
        ),
    ]
